volumes:
  db_data:
  static_assets:
  caches:
  paddlex-cache:

networks:
  web:

services:
  clepsy:
    image: ghcr.io/samgalanakis/clepsy:latest
    container_name: clepsy
    networks: [web]
    volumes:
      - db_data:/var/lib/clepsy
      - static_assets:/shared-static
      - caches:/var/lib/clepsy-caches
      - paddlex-cache:/root/.paddlex
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "${CLEPSY_PORT:-8000}:8000"
    environment:
      GOOSE_DRIVER: sqlite3
      GOOSE_DBSTRING: /var/lib/clepsy/db.sqlite3
      GOOSE_MIGRATION_DIR: ./migrations
