volumes:
  db_data:               # ‚Üê named volume for SQLite
  static_assets:
  caches:
networks:
  web:

services:
  clepsy:
    image: ghcr.io/samgalanakis/clepsy:latest
    container_name: clepsy
    networks: [web]
    volumes:
      - db_data:/var/lib/clepsy
      - static_assets:/shared-static
      - caches:/var/lib/clepsy-caches
    entrypoint: ["sh", "-c", "uvicorn clepsy.main:app --host 0.0.0.0 --port 8000 --workers 1"]
    secrets: [clepsy_password]
    ports:
      - "127.0.0.1:${CLEPSY_PORT:-8000}:8000"
    environment:
      GOOSE_DRIVER: sqlite3
      GOOSE_DBSTRING: /var/lib/clepsy/db.sqlite3
      GOOSE_MIGRATION_DIR: ./migrations
      PADDLE_OCR_BASE_DIR: /var/lib/clepsy-caches/paddle_cache



secrets:
  clepsy_password:
    file: ./clepsy_password.txt
